### ISSUE TITLE
Delivery.Commit can hang

### ISSUE THREAD

**Issue by codecat** [foxcpp/go-imap-sql#36]
When I start the following goroutine:
```go
d := be.base.NewDelivery()

go func() {
	for {
		time.Sleep(10 * time.Second)

		body := "From: admin@imap.test\n"
		body += "To: username@imap.test\n"
		body += "Subject: Automated test\n"
		body += "Content-Type: text/plain; charset=UTF-8\n\n"
		body += "Hello world\n"

		d.AddRcpt(viper.GetString("user.username"), textproto.Header{})
		d.BodyRaw(strings.NewReader(body))

		err := d.Commit()
		if err != nil {
			log.Error("Unable to commit: %s", err.Error())
			continue
		}

		log.Info("Created new message")
	}
}()
```
It's possible for `d.Commit()` to deadlock when Thunderbird has connected to the server, after which a bunch more stuff in the imap server locks up.

It locks up on this line:
https://github.com/foxcpp/go-imap-sql/blob/2f57903a7ed00b64fc5213322f8dc0b993e5a55b/delivery.go#L376

Am I doing something wrong, or is this a bug?

**Comment by codecat** [comment]
Looks like I needed to use the unused `Updates()` to manually receive updates, even if I don't use them. (The channel buffer was being filled up.) Not sure if that's intended.
```go
go func() {
	for {
		upd := <-be.base.Updates()
		log.Trace("Update from %s in %s", upd.Username(), upd.Mailbox())
	}
}()
```

**Comment by foxcpp** [comment]
You can set LazyUpdatesInit:true in Opts when initializing backend. This will disable updates generation unless Updates is called.

**Comment by codecat** [comment]
Thanks :)
