### ISSUE TITLE
Computation-intensive hash algorithms for passwords

### ISSUE THREAD

**Issue by foxcpp** [foxcpp/go-imap-sql#4]
Somebody raised some concerns about salted SHA3-512 being not enough to provide reasonable security. 

Thoughts?

**Comment by NamedKitten** [comment]
https://rietta.com/blog/2016/02/05/bcrypt-not-sha-for-passwords/

**Comment by emersion** [comment]
https://godoc.org/golang.org/x/crypto/bcrypt

**Comment by foxcpp** [comment]
On a second thought, I guess it might make sense when used together with encrypted server-side storage (emersion/maddy#10).

**Comment by foxcpp** [comment]
Added some code to the issue-4 branch. bcrypt is not used by defaul tho, my main concern with it is whether we can somehow remediate performance penalty of hash computation.

**Comment by emersion** [comment]
Why is this a concern?

**Comment by foxcpp** [comment]
It allows to easily create high CPU load on the server side, possibly making DoS/DDoS attacks easier.

**Comment by emersion** [comment]
Meh. I'd mitigate this by adding a delay in case of authentication failure and limiting per-IP requests (the latter is more of a sysadmin concern though).

**Comment by foxcpp** [comment]
Alright, bcrypt will be the default. Backend users (maddy) can either switch to sha3-512 or implement restrictions for authentication.

**Comment by foxcpp** [comment]
Merged issue-4 into dev.
