### ISSUE TITLE
Sorting sorts both by the selected criterion and UID

### ISSUE THREAD

**Issue by ptrcnull** [foxcpp/go-imap-sql#41]
Code in [`messageCompare(...)`](https://github.com/foxcpp/go-imap-sql/blob/946daf36ce81a5b82f8dfe814afcb57a07d0bfe7/sortthread.go#L103) with a valid sorting criterion still falls back to `return buf[i].ID < buf[j].ID` for some reason when it should return false.

**Comment by foxcpp** [comment]
From [RFC 5256](https://datatracker.ietf.org/doc/html/rfc5256):
>If two or more messages exactly match according to the sorting
>criteria, these messages are sorted according to the order in
>which they appear in the mailbox.  In other words, there is an
>implicit sort criterion of "sequence number".

**Comment by ptrcnull** [comment]
ah, okay, let me fix that

**Comment by ptrcnull** [comment]
```go
case "ARRIVAL":
	if buf[i].ArrivalUnix == buf[j].ArrivalUnix {
		continue
	}
	if crit.Reverse {
		return buf[i].ArrivalUnix > buf[j].ArrivalUnix
	} else {
		return buf[i].ArrivalUnix < buf[j].ArrivalUnix
	}
```
would this style be okay with you? or do you think there's a better way to handle that

**Comment by foxcpp** [comment]
That seems to do exactly what current code does, why change?

**Comment by ptrcnull** [comment]
not at all - it should fall back to the next criterion only if the current one is equal, currently it falls back when it's equal __or less__, which messes up the sorting entirely

you can see this just by opening your inbox in [aerc](https://aerc-mail.org/), which relies heavily on server-side sorting

**Comment by foxcpp** [comment]
Oh, I see.

> would this style be okay with you? 

Sure, lets go with this.
